name: bioskop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  youtube_player_flutter: ^9.0.0
  url_launcher: ^6.2.10
  shared_preferences: ^2.1.1   # âœ… ditambahkan untuk favorite
  overlay_support: ^2.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner/promo1.jpg
    - assets/banner/promo2.jpg
    - assets/banner/promo3.jpg
    - assets/banner/promo4.jpg
    - assets/banner/promo5.jpg
    - assets/banner/promo6.jpg
    - assets/banner/promo7.jpg
    - assets/banner/promo8.jpg
    - assets/banner/promo9.jpg
    - assets/banner/promo10.jpg
    - assets/banner/promo11.jpg
    - assets/banner/promo12.jpg
    - assets/banner/promo13.jpg
